### ISSUE TITLE
Text appended after the first character, not at the cursor

### ISSUE THREAD

**Issue by rafaqz** [Shougo/neoyank.vim#1]
I'm having issues with appending, using this command:

```
nnoremap [unite]p  :Unite -no-split     -default-action=append  -start-insert  history/yank<Return>
```

No matter where the cursor is in the line the text is pasted after the first character.

**Comment by rafaqz** [comment]
Seems this is a general unite issue, and it only happens with the -no-split flag.

**Comment by Shougo** [comment]
It is not neoyank issue.
Please create it in unite.vim issues.

**Comment by Shougo** [comment]
> No matter where the cursor is in the line the text is pasted after the first character.

And this is append action's feature.
The action pastes the text after the first character like `p` mapping.
You should use "insert" action.

**Comment by rafaqz** [comment]
I mean after the first character in the line, ie in the second column, not
after the cursor.  But its fine without -no-split and I'm happy with the
workaround.

**Comment by Shougo** [comment]
I think this problem is fixed in latest unite.
