### ISSUE TITLE
Incorrect usage of TextYankPost causes superfluous clipboard activity

### ISSUE THREAD

**Issue by bfredl** [Shougo/neoyank.vim#10]
On `TextYankPost` this plugin does `getreg(name), getregtype(name)` with a loop of different registers. This is very ineffficient and causes clipboard provider usage even if the register was not a clipboard (or even for an unnamed clipboard in a `g/xx/d` loop where nvim would've normally only copied on the last delete). Instead it should use `v:event.regname` to get the name of the register yanked to and the contents and type in `v:event.regcontents` and `v:event.regtype`

**Comment by Shougo** [comment]
Fixed.
