### ISSUE TITLE
sshを等してからneovimを使う際、neoyankをクライエントサイドのクリップボードプログラムにコンテンツを送ることができますか？

### ISSUE THREAD

**Issue by bravecorvus** [Shougo/neoyank.vim#12]
シュゴさん、
ニオヴィムのplugin開発ご苦労様です。おかげさまで、今では僕が日々 software development に使っているプログラムの中では、ニオヴィムが一番使われます。

これはかなり前からある質問なのですがsshを使っている時、sshクライエントとsshホストのクリップボードが違うため、ニオヴィムの中で```yー```を使用した場合、どこにもコピーされません。

具体的にホストがKali Linux, xfceの場合、使われるクリップボードソフトは xclip であり、クライエントがMacの場合そちらのソフトはpbcopy/pbpaste になります。どのようにしたら、Kali Linux の ssh セッションからMacのpbcopy にテキストを移すことができるのでしょうか？

僕の考えでは、scpなどのfile transfer protocolを使ってテキストを一時的にフィイルとして送り、クライエント側で　```cat temp | pbcopy``` などのcommandを使ってpbcopyにテキストを送る手法が思いついたのですが、実際、これをvimscriptでかく知識がないため、とりあえずシュゴさんの意見を伺いにきました。

今年僕は大学で、sys admin　の仕事があるため、大抵自分のMac 環境(environment)ではなく、sshを等して学校のサーバー環境で働くため、yank via sshが実現できたら効率アップに繋がります。よろしくお願いします。

Although I speak Japanese fluently, I took computer science in English, so if its easier to understand for you, we can communicate in English as well.

**Comment by Shougo** [comment]
You should use lemonade.

https://github.com/pocke/lemonade

```
							      *clipboard-tool*
The presence of a working clipboard tool implicitly enables the '+' and '*'
registers. Nvim looks for these clipboard tools, in order of priority:

  - |g:clipboard|
  - pbcopy/pbpaste (macOS)
  - xclip
  - xsel (newer alternative to xclip)
  - lemonade (for SSH) https://github.com/pocke/lemonade
  - doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
  - win32yank (Windows)
  - tmux (if $TMUX is set)
```
