### ISSUE TITLE
denite source is not same as unite source

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neoyank.vim#14]
@Shougo  I just want to improve denite layer in spacevim, and I found this plugin provide two sources are different.

in unite source we can see the content from register 0-9, but in denite source we can only see reigister `"`.

**Comment by Shougo** [comment]
@wsdjeg You must use `Denite register` instead.

**Comment by wsdjeg** [comment]
@Shougo hi, 

~~In unite `Unite registers` I can see all registers, included `0-9`, but when run `Denite registers`, I can only see `"`.~~

sorry, I think I must miss something, it works well for me now.
