### ISSUE TITLE
Configure the yankring paste position

### ISSUE THREAD

**Issue by wikimatze** [Shougo/neoyank.vim#2]
When using `p`, vim will paste the text right after the cursors, when chosing a line from yankring and pressing `p` and I press `Enter` it will paste the text in front of the cursor (like pressing `P` in normal mode). Is it possible to configure this setting?

**Comment by Shougo** [comment]
`insert` action is same with `P`.
`append` action is same with `p`.

You can specify the action.

**Comment by wikimatze** [comment]
I mean, when I call `:Unite history/yank<CR>` then I get a list of yanked text. When I found what I'm searching for, I press `<CR>` and the selection is appended like pressing `P` in normal mode but I would like to have the behavior when I press `<CR>` in the yank-ring result page to be like pressing `p` in normal mode.

**Comment by Shougo** [comment]
`:Unite history/yank -default-action=append<CR>`

**Comment by wikimatze** [comment]
Works perfect, thank you very much. I've updated the FAQ about this issue.
