### ISSUE TITLE
neoyank cause neovim wildmenu forget current selection after FocusGained when 'wildoptions'=pum

### ISSUE THREAD

**Issue by mars90226** [Shougo/neoyank.vim#21]
# Problem
When `'wildoptions'=pum`, tabbing through completions and switching to other process (like tmux switch pane) and switching back, then tab again, neovim will select second candidate.

# Environment
neovim version: NVIM v0.4.0-799-gb9ba1295b
OS: Ubuntu 18.04 LTS
tmux version: 2.8

# Minimal .vimrc
```
call plug#begin('~/.vim/plugged')

Plug 'Shougo/unite.vim'
Plug 'Shougo/neoyank.vim'

call plug#end()

set wildoptions+=pum
```

# Reproducible Steps
```
nvim -u minimal.vimrc
:h <Tab><Tab><Tab>
tmux-switching-other-pane
tmux-switching-back
<Tab>
```
These steps should select 4th candidate, but actually select 2nd candidate.

**Comment by Shougo** [comment]
It is not neoyank's problem.
Because neoyank does not change the cursor.

It seems `wildoptions=pum` problem.

**Comment by mars90226** [comment]
Hi, I've found that comment out [these two lines](https://github.com/Shougo/neoyank.vim/blob/master/autoload/neoyank.vim#L174-L175) in `s:is_sudo()` in `autoload/neoyank.vim` will prevent the problem. And I do use `root` as user. If I use normal user, the problem does not appear.

I think `expand()` should not change the cursor, so it's still a `wildoptions=pum` problem, right?

**Comment by mars90226** [comment]
The following .vimrc can trigger the same problem, so it's neovim's bug. I'll open an issue there, thank you!
```
set wildoptions=pum

augroup expand_in_focus_autocmd
  autocmd!
  autocmd FocusGained,FocusLost * call s:expand()
augroup END

function! s:expand()
  call expand('~')
endfunction
```
