### ISSUE TITLE
Sometimes neoyank.vim doesn't save/display the yanked text immediately across Vim instances

### ISSUE THREAD

**Issue by phongvcao** [Shougo/neoyank.vim#22]
Hi Shougo,

Sometimes my neoyank.vim doesn't save/display the yanked text immediately across Vim instances, especially if I yanked something in a Vim instance, then quickly move to another Vim instance or quickly closed the yanked Vim instance, then the text doesn't appear immediately in Unite buffer. 

I notice that the yank_history uses json. I wonder why is this the choice, given that json parsing can sometimes be very slow for large yank_history?

For bash_history for example bash just uses plain text file for its history and the result is almost immediate. The same goes for YankRing for example.

I wonder if neoyank.vim should just move to plain text files & use async to save the registers in the background?

(P/S: I'm mainly using YankRing.vim to substitute for not having either +clipboard or +xterm_clipboard in my remote server. Thus, YankRing.vim acts like a clipboard register for me. I have been trying to integrate neoyank.vim to replace YankRing.vim in this regard but haven't been able to do that. I love Unite.vim & would like to use it for everything.)

**Comment by Shougo** [comment]
What is your Vim version?

This plugin is optimized for the latest Vim/neovim.

**Comment by Shougo** [comment]
I have read the code.
It should work.  But if your machine is slow, and your switch is very fast, no garantee for synched.

**Comment by Shougo** [comment]
You can configure `g:neoyank#limit` and `g:neoyank#length`.

**Comment by Shougo** [comment]
And you can check the current `g:neoyank#file` size.

> I wonder if neoyank.vim should just move to plain text files & use async to save the registers in the background?

No.
