### ISSUE TITLE
Action yank acts weirdly

### ISSUE THREAD

**Issue by mrdgo** [Shougo/neoyank.vim#24]
When I yank a line then yank the next line, then use `:Denite neoyank -default-action=yank`
I would expect to have `line content` in my register.
But actually I have `+: line content\n`

Is there a simple fix, that I have overseen?

**Comment by Shougo** [comment]
You should check your register value by `:registers`.
It contains new line in the end.
neoyank plugin prints it as `\n`.

**Comment by Shougo** [comment]
And `+` means clipboard register.
I think you have set clipboard option.

**Comment by mrdgo** [comment]
I used `:registers` to  inspect the registers and it showed `+: line content\n`

I understand, thank you very much! I just changed this in the `neoyank.py` to satisfy my needs.

Edit: I totally forgot to mention, I appreciate your work. You are awesome :)

**Comment by Shougo** [comment]
:-)
