### ISSUE TITLE
Inconsistent behavior between p and neoyank/action for line yank

### ISSUE THREAD

**Issue by ikeji** [Shougo/neoyank.vim#25]
I have a buffer like this ( "|" is cursor ):
```
fo|o
bar
buzz
```
I yanked entire line 1 by "yy" command and move cursor to "a" in line2:
```
foo
b|ar
buzz
```

A. When I type "p" buffer will changed like this:
```
foo
bar
|foo
buzz
```
"p" insert the yanked text to next line.

B. When I run "Unite history/yank" and select first item.
```
foo
|foo
bar
buzz
```
"Unite history/yank" insert the yanked text to previous line.

C. when i run "Denite neoyank" and select first item.
```
foo
b|foo
ar
buzz
```
"Denite neoyank" insert the yanked text to the cursor position.

I expect that B and C is consist with A.

(I use head version of neoyank.vim and vim8.1.1401)

**Comment by Shougo** [comment]
`:Unite history/yank` uses `insert` action is default.  This is `P` behavior.
If you want to use `p` behavior, you need to use `append` action instead.

**Comment by Shougo** [comment]
> "Denite neoyank" insert the yanked text to the cursor position.

I have fixed the problem.  Please use the latest version of both denite and neoyank.

**Comment by ikeji** [comment]
Thanks for quick fix! I confirmed that the current head has expected behavior.
