### ISSUE TITLE
Updating yank history from multiple files simultaneously

### ISSUE THREAD

**Issue by junkmechanic** [Shougo/neoyank.vim#6]
Hi,
I would like to understand the exact nature of this source (or probably this is more a unite thing).
1. Is the yank history loaded from the history_yank cache file once when vim is started or is it updated synchronously? Let's say I have two instances of vim open. If I yank some text from one of the these, should I expect the yanked text to appear in the second instance if I initiate :unite history/yank after yanking from the first instance? Currently I dont see that happening in my setup. So I wonder if that's expected behavior.
2. Sometimes the yanks appear at the bottom of the results. Is that also expected?

Thanks!

**Comment by Shougo** [comment]
> Is the yank history loaded from the history_yank cache file once when vim is started or is it updated synchronously? Let's say I have two instances of vim open. If I yank some text from one of the these, should I expect the yanked text to appear in the second instance if I initiate :unite history/yank after yanking from the first instance? Currently I dont see that happening in my setup. So I wonder if that's expected behavior.

Yes.  It is already implemented.  But it is saved in `WinEnter,BufWinEnter,CursorMoved,FocusGained,FocusLost` events.

> Sometimes the yanks appear at the bottom of the results. Is that also expected?

I cannot reproduce it.  Please create reproduce ways.

**Comment by Shougo** [comment]
> Sometimes the yanks appear at the bottom of the results. Is that also expected?

I get it.  It is feature.
If the history is updated, your yanks appear at the bottom.

**Comment by junkmechanic** [comment]
Hi @Shougo ,

Thanks for your reply.
Regarding my first query, could you please elaborate a little more. Let's say,
1. I have vim instances opened in _two different windows of tmux_.
2. I yank some text from the vim instance in window 1.
3. I change to window 2,  which has the other vim instance. There I do `:Unite history/yank<CR>`.
4. Should I expect the text yanked from window 1 to appear in the unite buffer. Currently, in my setup, it doesnt appear.

Events `CursorMoved, FocusGained, FocusLost` take affect within the vim instance that the text has been yanked from. I dont think it would matter in this case.

Thanks

**Edit**
Only when I exit vim from window 1 does the history get updated. Then opening history/yank in window 2 vim shows the text that was yanked from window 1.

**Comment by Shougo** [comment]
It is feature.
You must move cursor to save the yanked text.
neovim does not have the problem.
It implements YankPost events.

**Comment by junkmechanic** [comment]
Sure. Moving the cursor saves the yanked text. **But** it is still not visible in a different instance of vim. I checked the cache file too. The yanked text was not updated there.

**Unless** I close the vim instance that the text was yanked from. Then the cache file is updated. So this means that neoyank updates the cache file only while exiting ( :q or :qa ), not even on BufLeave (I had checked that too).

If you could let me know how that happens, I wouldnt mind calling the function manually too.

Thanks!

**Comment by Shougo** [comment]
tmux is not Vim's feature.
You should use `:split`.

**Comment by junkmechanic** [comment]
Oh no, this is not concerning tmux. That was just way to represent two different instances of vim.
I think I found a way to describe my problem. Following are the steps to reproduce it.
1. Open vim file1.
2. Copy some text.
3. `:call neoyank#_save()`
4. Check cache file ( `$XDG_CACHE/neoyank/history_yank` ). You will notice that the yanked text is **not** there.
5. Now exit file1  :  `:q` .
6. Check cache file. Now the yanked text is updated.

Is it possible to update the cache file without exiting vim?

Let me know if you can't reproduce this.

**Comment by Shougo** [comment]
No.  You must call `neoyank#_append()`.

**Comment by junkmechanic** [comment]
That doesnt help either. Same result. The cache file is not updated on calling `neoyank#_append`. Can you reproduce this?

Is this a problem of flushing the contents to be written to the file?

**Comment by Shougo** [comment]
@junkmechanic I have added `neoyank#update()`.  Please use it.

**Comment by Shougo** [comment]
@junkmechanic neoyank ignores the duplicated yanked text or too long text.
Please check it.

**Comment by junkmechanic** [comment]
@Shougo 
I confirm that it works now. I can see the change in the cache file on yanking text.

Many thanks!!
